name        : autogen
version     : 5.18.4
release     : 6
source      :
    - http://ftp.gnu.org/gnu/autogen/rel5.18.4/autogen-5.18.4.tar.gz : 3cd9f81a8ae7c6865bb9bbbe16c4307a243a1373d0b315a83571cbba1fff725d
homepage    : http://www.gnu.org/software/autogen/
license     :
    - GPL-3.0
summary     : Program generation tool
builddeps   :
    - pkgconfig(guile-2.0)
    - pkgconfig32(guile-2.0)
    - pkgconfig(bdw-gc)
    - pkgconfig32(bdw-gc)
    - glibc-32bit-devel
    - libgcc-32bit
    - libstdc++-32bit
emul32      : yes
description : |
    AutoGen is a tool designed to simplify the creation and maintenance of programs that contain large amounts of repetitious text. It is especially valuable in programs that have several blocks of text that must be kept synchronized.
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
