name       : autogen
version    : 5.18.7
release    : 7
source     :
    - https://ftp.gnu.org/gnu/autogen/autogen-5.18.7.tar.xz : a7a580a5e18931cb341b255cec2fee2dfd81bea5ddbf0d8ad722703e19aaa405
homepage   : http://www.gnu.org/software/autogen/
license    :
    - GPL-3.0
summary    :
    - Program generation tool
    - libs: Runtime libraries for autogen, libopt
component  : programming.tools
patterns   :
    - libs :
        - /usr/lib64/*.so.*
replaces   :
    - libs: libautogen
builddeps  :
    - pkgconfig(guile-2.0)
    - pkgconfig32(guile-2.0)
    - pkgconfig(bdw-gc)
    - pkgconfig32(bdw-gc)
emul32     : yes
description: |
    AutoGen is a tool designed to simplify the creation and maintenance of programs that contain large amounts of repetitious text. It is especially valuable in programs that have several blocks of text that must be kept synchronized.
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
