name       : autogen
version    : 5.18.16
release    : 8
source     :
    - https://ftp.gnu.org/gnu/autogen/autogen-5.18.7.tar.xz : a7a580a5e18931cb341b255cec2fee2dfd81bea5ddbf0d8ad722703e19aaa405
homepage   : https://www.gnu.org/software/autogen/
license    : GPL-3.0-or-later
component  :
    - programming.tools
    - libs : programming.library
summary    :
    - Program generation tool
    - libs : Runtime libraries for autogen, libopt
description: |
    AutoGen is a tool designed to simplify the creation and maintenance of programs that contain large amounts of repetitious text. It is especially valuable in programs that have several blocks of text that must be kept synchronized.
patterns   :
    - libs :
        - /usr/lib64/*.so.*
replaces   :
    - libs : libautogen
emul32     : yes
builddeps  :
    - pkgconfig32(bdw-gc)
    - pkgconfig32(guile-2.0)
setup      : |
    # Disable failing tests
    sed -e 's|usage.test||' -e 's|getopt.test||' -i autoopts/test/Makefile.in
    sed -e 's|error.test||' -i agen5/test/Makefile.in

    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
